MAX_ERROR_CNT = 20
MAX_BACKOFF_SEC = 30
MAX_NEXT_BATCH_NOT_AVAILABLE_CNT = 50
RETRY_PAUSE_SEC = 5
END_OF_QUEUE = (-1, "exiting")

API_URL_FORMAT = "{}://{}/api"

DEFAULT_HSM_THREADS = 20
DEFAULT_HSM_SLOT = 1